server:
  port: 8040
spring:
  application:
    name: zuul-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    alarm-server-route:
      serviceId: alarm-server
      path: /**/alarm/**
    device-server-route:
      serviceId: device-server
      path: /**/findAlarmByDevice/**
    right-server-route:
      serviceId: right-server
      path: /**/register/**